repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.4
    hooks:
      - id: ruff-format
      - id: ruff
        args: [--fix]

  - repo: https://github.com/astral-sh/ty-pre-commit
    rev: ty-0.0.1a12
    hooks:
      - id: ty
